# Sanity check for embeddings.npy

In [2]:
import numpy as np
import pandas as pd

In [25]:
BOOK_ID_PATH = "/home/claraoberle/personal-book-recommender/data/embedding/book_ids.npy"
EMBEDDINGD_PATH = "/home/claraoberle/personal-book-recommender/data/embedding/embeddings.npy"
CLEAN_DF_PATH = "/home/claraoberle/personal-book-recommender/data/clean/goodreads_clean.csv"

In [26]:
book_ids = np.load(BOOK_ID_PATH, allow_pickle=True)
embeddings = np.load(EMBEDDINGD_PATH, allow_pickle=True)
clean_df = pd.read_csv(CLEAN_DF_PATH)

I will check the top similarity books to several read books and see if the match is reasonable.

In [39]:
def print_top_similarities(book_id, embeddings, clean_df, book_ids):
    # find the vector for the hunger games
    idx = np.where(book_ids == book_id)[0][0]
    query_vector = embeddings[idx]

    # Calculate similarity with every other book
    similarities = embeddings @ query_vector

    # make the similarity with itself -1 and sort similarities
    similarities[idx] = -1
    top_indices = np.argsort(similarities)[-5:][::-1]

    results = clean_df[clean_df["Book Id"].astype(str).isin(book_ids[top_indices])].copy()

    results["similarity"] = [
        similarities[np.where(book_ids == str(book_id))[0][0]]
        for book_id in results["Book Id"]
    ]
    
    return results[["Book Id", "Title", "similarity"]].sort_values(
            "similarity", ascending=False
        )

In [42]:
the_hunger_games_id = "2767052"
el_señor_de_los_anillos = "222947"
paper_towns = "6442769"
the_selection = "10507293"

print_top_similarities(the_hunger_games_id, embeddings, clean_df, book_ids)

       Book Id                                              Title  similarity
168    6148028               Catching Fire (The Hunger Games, #2)    0.693397
86   183526560  Dune (edición especial película) (Las crónicas...    0.631514
106    1908374                                              Aloma    0.604867
173          6  Harry Potter and the Goblet of Fire (Harry Pot...    0.548952
91    15749186  To All the Boys I've Loved Before (To All the ...    0.547155

In [43]:
print_top_similarities(el_señor_de_los_anillos, embeddings, clean_df, book_ids)

      Book Id                                              Title  similarity
36    7183286         El imperio final (Nacidos de la bruma, #1)    0.614532
67   10664113  A Dance with Dragons (A Song of Ice and Fire, #5)    0.604951
151         1  Harry Potter and the Half-Blood Prince (Harry ...    0.559236
172         2  Harry Potter and the Order of the Phoenix (Har...    0.547279
34    7235533      The Way of Kings (The Stormlight Archive, #1)    0.540361

In [44]:
print_top_similarities(paper_towns, embeddings, clean_df, book_ids)

      Book Id                                            Title  similarity
20   54493401                                Project Hail Mary    0.577395
35      68429             The Well of Ascension (Mistborn, #2)    0.528333
146  36307634                King of Scars (King of Scars, #1)    0.510153
7    54189398  The Spanish Love Deception (Love Deception, #1)    0.502625
21      11334                                  Song of Solomon    0.501691

In [45]:
print_top_similarities(the_selection, embeddings, clean_df, book_ids)

       Book Id                                              Title  similarity
155   16248068                      The Elite (The Selection, #2)    0.579982
16    21415180                                  Regreso a tu piel    0.490199
121   18126198  Four: A Divergent Story Collection (Divergent,...    0.462148
124   10429045                        Shatter Me (Shatter Me, #1)    0.449603
15   115559438                               Parable of the Sower    0.402897